name: CI Pipeline

# מתי הצינור הזה ירוץ? בכל פעם שדוחפים קוד לענף הראשי
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # המכונה הווירטואלית שתריץ את הבדיקות

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # התקנת כלי הבדיקה
        pip install flake8 pytest httpx
        # התקנת הספריות של הפרויקט
        pip install -r backend/requirements.txt

    - name: Run Linter (Code Checks)
      run: |
        # בודק שגיאות תחביר חמורות בקוד. 
        # --exit-zero מבטיח שהבדיקה לא תכשיל את כל הצינור בגלל רווחים חסרים
        flake8 backend/ --count --exit-zero --max-line-length=127 --statistics

    - name: Run Unit Tests
      run: |
        cd backend
        pytest test_main.py -v